name: Publish

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      UV_FROZEN: 1
    steps:
    - uses: actions/checkout@v4
    - name: Configure Git Credentials
      run: |
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
    - name: Install uv
      uses: astral-sh/setup-uv@v6
    - name: Install the project
      run: uv sync --locked --all-extras --dev
    - name: Bump version
      run: uv version ${{ github.event.release.tag_name }}
    - name: Build
      run: uv build
    - name: Publish package
      run: uv publish -t ${{ secrets.PYPI_TOKEN }}
    - id: get_version
      uses: battila7/get-version-action@v2
    - name: Git Fetch Docs
      run: git fetch origin gh-pages --depth=1
    - name: Publish Docs
      run: uv run mike deploy --push --update-aliases ${{ steps.get_version.outputs.major }}.${{ steps.get_version.outputs.minor }} latest
